version: '3'

services:

  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: always
    networks:
      - oreilly
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"

  app:
    image: oreilly-api:latest
    container_name: oreilly
    restart: always
    networks:
      - oreilly
    ports:
      - 80:80
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      FLASK_ENV: "${FLASK_ENV}"
      SECRET_KEY: "${SECRET_KEY}"

networks:
  oreilly: