---
apiVersion: v1
kind: Service
metadata:
  name: oreilly-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: oreilly-api
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres
